### ISSUE TITLE
trying to port wct transfer to numpy.

### ISSUE THREAD

**Issue by iperov** [clovaai/WCT2#1]
torch and numpy svd are different

```
u, e, v = torch.svd(conv, some=False)
ut, et, vt = [ x.data.cpu().numpy() for x in (u,e,v) ]
un, en, vn = np.linalg.svd ( conv.data.cpu().numpy() )
print ("diff=", np.sum(np.abs(ut-un)))
print ("diff=", np.sum(np.abs(et-en)))
print ("diff=", np.sum(np.abs(vt-vn)))
```

result:

```
diff= 10380.845
diff= 0.007629454
diff= 12652.448
```

`scipy.linalg.svd` - same wrong result

diff with tensorflow:
```
import tensorflow as tf
    tf_sess = tf.Session(config=tf.ConfigProto(device_count={'GPU': 0}) )
    tf_inp = tf.placeholder(tf.float32, shape=conv.shape )

    tfe, tfu, tfv = tf.linalg.svd( tf_inp, full_matrices=True ) #conv.data.cpu().numpy() )

    tfe, tfu, tfv =  tf_sess.run ([tfe, tfu, tfv], feed_dict={tf_inp: conv.data.cpu().numpy() } )
    print ("diff=", np.sum(np.abs(ut-tfu)))
    print ("diff=", np.sum(np.abs(et-tfe)))
    print ("diff=", np.sum(np.abs(vt-tfv)))
```
```
diff= 10259.318
diff= 0.03329885
diff= 10259.33
```

so is your net trained with torch.svd , and there is no way to use your method in other frameworks?

found similar issue pytorch/pytorch#16076
but it is closed

**Comment by iperov** [comment]
found similar issue https://github.com/pytorch/pytorch/issues/16076
but it is closed

**Comment by soumith** [comment]
hey @iperov if you see, the diff with tensorflow is also pretty large.

What you are looking at is two different singular value decompositions, both being mathematically correct.
With SVD, you dont need to have a bitwise same result to come back to have a correct answer.

hope this helps.

**Comment by vishwakftw** [comment]
@iperov You should probably use `np.sum(np.abs(ut)-np.abs(un))` and `np.sum(np.abs(vt)-np.abs(vn))` since the singular vectors can have opposite signs.

Note that if USV^T is a valid SVD, then (-U)S(-V)^T is also a valid SVD.

**Comment by iperov** [comment]
@soumith 
> if you see, the diff with tensorflow is also pretty large.

no. 
`( numpy.svd == scipy.svd == tf.svd ) != torch.svd`

**Comment by iperov** [comment]
@vishwakftw ok I will continue to port, and check final result.

**Comment by jaejun-yoo** [comment]
@iperov First of all, the network training is totally an independent procedure. It is trained for image reconstruction task on MSCOCO dataset. If you are familiar with WCT, this is why their method can stylize arbitrary images with arbitrary styles. After finishing the network training on image reconstruction, we use the pre-trained weight and stylize the features using SVD, which has nothing to do with training. 
Secondly, as @soumith pointed out, SVD can provide multiple valid solutions.
