### ISSUE TITLE
Can I  train with my data?

### ISSUE THREAD

**Issue by skh0619** [clovaai/WCT2#11]
Hello. Thank you for sharing your good research. 
Can I try to train with my data? If I can, please explain the command and method . 
Thank you in advance.

**Comment by jaejun-yoo** [comment]
Hi, thank you for paying your attention to our study. Currently, we did not upload the training code yet (planning to...). However, if you are interested, you can get the model without calling the decoder weights and train it on your own data. This previous issue might be helpful: https://github.com/clovaai/WCT2/issues/7#issuecomment-498301763
