### ISSUE TITLE
Query regarding "conv0" layer

### ISSUE THREAD

**Issue by divyagaddipati** [clovaai/WCT2#13]
Could you please explain the reason for using the "conv0" layer, as it is not part of the original VGG19? Also, during training, are the weights of this particular layer set as trainable or fixed?

**Comment by jaejun-yoo** [comment]
Dear @divyajyothig 
Hi. Thank you for your interest on our project! Regarding "conv0" layer, it is inherited from the previous work "PhotoWCT", which used the same layer in front of the VGG19 network architecture. If you look into the weights of the layer, you will find that it is fixed (untrainable). Actually, the function of the conv0 layer is to normalize the raw RGB image pixel value into the certain range. 
I hope this would help your understanding :)

---
If you find this project is useful or interesting, please consider ⭐️ and watch our repo. Thanks!
