### ISSUE TITLE
Error with installing requirements

### ISSUE THREAD

**Issue by pniedzwiedzinski** [clovaai/WCT2#2]
On google colab it's failing to install when I do `pip3 install -r requirements.txt` 

```
Could not find a version that satisfies the requirement torch==0.4.1.post2 (from -r requirements.txt (line 1)) 
(from versions: 0.1.2, 0.1.2.post1, 0.3.1, 0.4.0, 0.4.1, 1.0.0, 1.0.1, 1.0.1.post2)
No matching distribution found for torch==0.4.1.post2 (from -r requirements.txt (line 1))
```

**Comment by jaejun-yoo** [comment]
@pniedzwiedzinski Thx. I changed the requirements.txt. You can simply open the requirement.txt and erase the 0.4.1**.post2** part. I checked that torch == 0.4.1 works.
