### ISSUE TITLE
some questions about the figure 9

### ISSUE THREAD

**Issue by hello-trouble** [clovaai/WCT2#20]
Thank you for your good job ! I have a problem that how to computer the value of SSIM and Gram loss of Figure 9?

**Comment by youngjung** [comment]
We run HED [32] to convert input and output to edge images and then compute SSIM between them.
Gram loss is covariance difference between feature embeddings (VGG19) of input and output images. Please refer to [8] for more details.

**Comment by 13462877152** [comment]
Thank you for your help.  Could you supply the code for computer the SSIM?  I adopt the code of ski-image (skimage.measure import compare_ssim) to compute SSIM between edges of DPST and content images, the result is about 0.6840, I don't know what's wrong with it.

**Comment by jaejun-yoo** [comment]
Were this resolved? There were some people that asked us the same code by email, and we gave them so that I am a little confused if this is the case.

**Comment by 13462877152** [comment]
Thank you very much for your help.
