### ISSUE TITLE
How to add temporal consistency

### ISSUE THREAD

**Issue by fantasy-fish** [clovaai/WCT2#21]
Hi , I want to transfer color for the video data. I was wondering how to add temporal consistency constraint such as optical flow on the model.

**Comment by youngjung** [comment]
Hi, thanks for your interest.
Our model works well without extra hint for temporal consistency because it preserves everything in the input frames except style.
Sharing your result would be helpful to us and others :)

**Comment by fantasy-fish** [comment]
![content](https://user-images.githubusercontent.com/28527546/77383398-0e17d980-6d40-11ea-8243-d20d3628d90a.gif)
![co26](https://user-images.githubusercontent.com/28527546/77383577-87afc780-6d40-11ea-83fa-5e2d2c1e107e.png)
![output](https://user-images.githubusercontent.com/28527546/77383472-3a335a80-6d40-11ea-8252-926f1b9d14a6.gif)
From top to below are content video, style image and the output video.
I know there's some lighting changes in the original video, but I don't know if there's anything I can do to improve the temporal consistency, such as adding temporal average smoothing on the WCT operations?
