### ISSUE TITLE
Could you please explain the idea of passing on the information captured by low frequency filters of wavelet pooling to encoder layer while the high frequency components are skip connected to decoder module directly?

### ISSUE THREAD

**Issue by AdarshMJ** [clovaai/WCT2#5]
In section 3 of your paper, where you discuss the model architecture, there is this paragraph - 

> "The max-pooling layers are replaced with wavelet pooling where high frequency components (LH,HL, HH) are skipped to the decoder directly. Thus, only the low frequency component (LL) is passed to the next encoding layer"

Is there a particular reason for this?

**Comment by jaejun-yoo** [comment]
@AdarshMJ Hi. It inherits the idea of wavelet decomposition, which recursively decomposes the low-filtered image. You can see the intuitive example by checking the [wikipedia](https://en.wikipedia.org/wiki/Wavelet_transform).
